title: Mathai Sibu Kombasseril # your name (or website title) here
logo: "/images/Profile Photo 1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist | Business Consultant and Strategist
  <br><br>
  Freelancing @ <a href="https://www.around-zero.com/" target="_blank">Around Zero Ltd</a>
  <br><br>
  "Driven Data Scientist with a strategic mindset and Masters in Computer Science and Data Science. Passionate about using software and data to swiftly address crucial emission challenges in travel, food, and energy."
  <br><br>
  <a href="https://www.linkedin.com/in/mathai-k-78437a2a2/" target="_blank">View my LinkedIn Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colours:
  crimson: '#900C3F'
